export type Question = {
  id: number;
  topic: string;
  question: string;
  correctAnswer: string;
};

const capitalBudgetingQuestions: Question[] = [
  {
    id: 1,
    topic: "Capital Budgeting",
    question: "What is Capital Budgeting?",
    correctAnswer: "Capital budgeting is the process of planning and evaluating expenditures on assets whose cash flows are expected to extend beyond one year. It involves analyzing potential major projects or investments to determine whether they will generate sufficient returns to justify the investment."
  },
  {
    id: 2,
    topic: "Capital Budgeting",
    question: "What is Net Present Value (NPV)?",
    correctAnswer: "NPV is the difference between the present value of cash inflows and the present value of cash outflows over a period of time. A positive NPV indicates that the projected earnings generated by a project or investment exceed the anticipated costs, in present dollars."
  },
  {
    id: 3,
    topic: "Capital Budgeting",
    question: "What is Internal Rate of Return (IRR)?",
    correctAnswer: "IRR is the discount rate that makes the NPV of all cash flows from a particular project equal to zero. It represents the expected compound annual rate of return that will be earned on a project or investment."
  }
];

const waccQuestions: Question[] = [
  {
    id: 4,
    topic: "WACC",
    question: "What is Weighted Average Cost of Capital (WACC)?",
    correctAnswer: "WACC is the average rate that a company expects to pay to finance its assets. It is calculated by weighting the cost of each capital component (debt and equity) by its proportional use in the company's capital structure."
  },
  {
    id: 5,
    topic: "WACC",
    question: "How is WACC calculated?",
    correctAnswer: "WACC = (E/V × Re) + (D/V × Rd × (1−Tc)), where E is market value of equity, D is market value of debt, V is total value of capital (E + D), Re is cost of equity, Rd is cost of debt, and Tc is corporate tax rate."
  }
];

const valuationQuestions: Question[] = [
  {
    id: 6,
    topic: "Valuation",
    question: "What is the Dividend Discount Model (DDM)?",
    correctAnswer: "The DDM is a method of valuing a company's stock price based on the theory that its stock is worth the sum of all of its future dividend payments, discounted back to their present value."
  },
  {
    id: 7,
    topic: "Valuation",
    question: "What is the Gordon Growth Model?",
    correctAnswer: "The Gordon Growth Model is a version of the DDM that assumes dividends will grow at a constant rate indefinitely. The formula is P = D1/(r-g), where P is current stock price, D1 is expected dividend next year, r is required rate of return, and g is growth rate of dividends."
  }
];

// Combine all questions into a single array
export const questions: Question[] = [
  ...capitalBudgetingQuestions,
  ...waccQuestions,
  ...valuationQuestions
];